export enum CustomError {
    INVALID_TOKEN = 'INVALID_TOKEN',
    FORBIDDEN = 'FORBIDDEN',
    INVALID_USERNAME_OR_PASSWORD = 'INVALID_USERNAME_OR_PASSWORD',
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
    INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
}
